### ISSUE TITLE
Allow valohai-yaml to accept external merge_strategy

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-yaml#33]
In `valohai-utils` branch `removeyaml2`, there is the most current version of valohai-utils. It now uses the old `MergeMode` and all the tests pass against the `valohai-yaml` branch `mergeconfig`. Convert it to the new `merge_strategy` parameter in the `valohai-yaml` branch `mergeconfig2`.

In `valohai-yaml` branch `mergeconfig2`, there is the most current WIP of the `merge_strategy` parameter. This needs to be finished.

See: https://github.com/valohai/valohai-yaml/pull/28

**Comment by akx** [comment]
This has apparently been marked done in 2020.
